name: Enviar correo

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Cambios realizados en la rama ${{ github.ref }}
          to: |
            alberto.renteriac@iteso.mx,
            yyamilecg2108@gmail.com
          from: avidrio39@gmail.com
          body: Cambios realizados en la rama ${{ github.ref }}
