name: Enviar correo

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:  
      - name: Send mailer
        if: ${{ always() }}
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.google.com
          # Optional port (defaults to 465)
          port: 465
          account: avidrio39@gmail.com
          password: Yoamoelrap123?
          sender: ducho
          from: avidrio39@gmail.com
          to: |
           alberto.renteriac@iteso.mx,
           yyamilecg2108@gmail.com
          subject: Se hicieron cambios en la rama ${{ github.ref }}.
          body: Se han pusheado cambios a la rama ${{ github.ref }}
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
